[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328new
framework = arduino

monitor_speed = 115200

lib_deps =
    teemuatlut/TMCStepper
    arduino-libraries/Servo

; Some newer official Nano boards use a different bootloader.
; If upload synchronization fails, try changing the board line to:
; board = nanoatmega328new
monitor_echoi= yes
monitor_eol= LF
monitor_filters= send_on_enter