[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328new
framework = arduino

monitor_speed = 115200

lib_deps =
    teemuatlut/TMCStepper
    arduino-libraries/Servo

; Show what you type
monitor_echo = yes

; Send a newline when Enter is pressed
monitor_eol = LF

; Let you type a complete command, then send it with Enter
monitor_filters = send_on_enter
